auto-detect and use wofi for Wayland and rofi for X11

diff --git a/rofi-radio b/rofi-radio
--- a/rofi-radio
+++ b/rofi-radio
@@ -4,13 +4,10 @@
 ARGS="--no-video"
 
 notification(){
-# change the icon to whatever you want. Make sure your notification server 
-# supports it and already configured.
-
-# Now it will receive argument so the user can rename the radio title
-# to whatever they want
-
-	notify-send "Playing now: " "$@" --icon=media-tape
+    # notify the user of the current stream being played
+    # change the icon to whatever you want. make sure your notification server 
+    # supports it and already configured.
+    notify-send "Playing now: " "$@" --icon=media-tape
 }
 
 # number of the stream as per the $choice variable
@@ -18,74 +15,83 @@ notification(){
 # additional tag to filter similar type of streams
 
 menu(){
-	printf "1. Lofi Girl <lofi>\n"
-	printf "2. Chillhop <lofi>\n"
-	printf "3. Box Lofi <lofi>\n"
-	printf "4. The Bootleg Boy <lofi>\n"
-	printf "5. Radio Spinner <lofi>\n"
-	printf "6. Dreamhop <lofi>\n"
-	printf "7. NDTV 24x7 <news>\n"
-	printf "8. WION Live <news>\n"
+    printf "1. Lofi Girl\n"
+    printf "2. Chillhop\n"
+    printf "3. Box Lofi\n"
+    printf "4. The Bootleg Boy\n"
+    printf "5. Radio Spinner\n"
+    printf "6. Dreamhop\n"
+    printf "7. NDTV 24x7\n"
+    printf "8. WION Live\n"
+}
+
+get_choice() {
+    # auto-detect and use wofi for Wayland and rofi for X11
+    if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
+        choice=$(menu | wofi --show dmenu)
+    elif [ "$XDG_SESSION_TYPE" = "x11" ]; then
+        choice=$(menu | rofi -dmenu)
+    else
+        echo "Unsupported session type: $XDG_SESSION_TYPE"
+        exit 1
+    fi
+    echo "$choice"
 }
 
 main() {
-	choice=$(menu | rofi -dmenu | cut -d. -f1)
+    choice=$(get_choice)
 
-	case $choice in
-		1)
-			notification "Lofi Girl ☕️🎶";
+    case "$choice" in
+        "1. Lofi Girl")
+            notification "Lofi Girl ☕️🎶"
             URL="https://youtu.be/jfKfPfyJRdk"
-	    ADDITIONAL_ARGS="--volume=60"
-			break
-			;;
-		2)
-			notification "Chillhop ☕️🎶";
+            ADDITIONAL_ARGS="--volume=60"
+            ;;
+        "2. Chillhop")
+            notification "Chillhop ☕️🎶"
             URL="https://youtu.be/7NOSDKb0HlU"
-	    ADDITIONAL_ARGS="--volume=60"
-			break
-			;;
-		3)
-			notification "Anime Lofi nostalgic ☕️🎶";
+            ADDITIONAL_ARGS="--volume=60"
+            ;;
+        "3. Box Lofi")
+            notification "Anime Lofi nostalgic ☕️🎶"
             URL="https://youtu.be/WDXPJWIgX-o"
-	    ADDITIONAL_ARGS="--volume=60"
-			break
-			;;
-		4)
-			notification "The Bootleg Boy ☕️🎶";
+            ADDITIONAL_ARGS="--volume=60"
+            ;;
+        "4. The Bootleg Boy")
+            notification "The Bootleg Boy ☕️🎶"
             URL="https://youtu.be/WIU-A596KKU"
-	    ADDITIONAL_ARGS="--volume=60"
-			break
-			;;
-		5)
-			notification "Radio Spinner ☕️🎶";
+            ADDITIONAL_ARGS="--volume=60"
+            ;;
+        "5. Radio Spinner")
+            notification "Radio Spinner ☕️🎶"
             URL="https://live.radiospinner.com/lofi-hip-hop-64"
-	    ADDITIONAL_ARGS="--volume=60"
-			break
-			;;
-		6)
-			notification "Dreamhop ☕️🎶";
+            ADDITIONAL_ARGS="--volume=60"
+            ;;
+        "6. Dreamhop")
+            notification "Dreamhop ☕️🎶"
             URL="https://youtu.be/wkhLHTmS_GI"
-	    ADDITIONAL_ARGS="--volume=60"
-			break
-			;;
-		7)
-			notification "NDTV 24x7 📰";
+            ADDITIONAL_ARGS="--volume=60"
+            ;;
+        "7. NDTV 24x7")
+            notification "NDTV 24x7 📰"
             URL="https://youtu.be/WB-y7_ymPJ4"
-	    ADDITIONAL_ARGS=""
-			break
-			;;
-		
-		8)
-			notification "WION Live 📰"
+            ADDITIONAL_ARGS=""
+            ;;
+        "8. WION Live")
+            notification "WION Live 📰"
             URL="https://youtu.be/lmZRiDMK3OU"
-	    ADDITIONAL_ARGS=""
-			break
-			;;
-		
-		esac
+            ADDITIONAL_ARGS=""
+            ;;
+        *)
+            echo "Invalid choice"
+            exit 1
+            ;;
+    esac
+
     # run mpv with args and selected url
     # added title arg to make sure the pkill command kills only this instance of mpv
     mpv $ARGS --title="radio-mpv" $URL $ADDITIONAL_ARGS
 }
 
+# kill any existing instance of script before starting a new one
 pkill -f radio-mpv || main
